name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Install PyQt6 system dependencies (EGL, XKB, etc.)
    - name: Install system dependencies for PyQt6
      run: |
        sudo apt-get update
        sudo apt-get install -y libxkbcommon-x11-0 libegl-mesa0 mesa-utils

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-qt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude fossil-main,ex/benchmarks-deterministic/FOSSIL-versions
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude fossil-main,ex/benchmarks-deterministic/FOSSIL-versions

    - name: Run tests with pytest
      env:
        QT_QPA_PLATFORM: offscreen
        AUTO_CLOSE_GUI: "1"
      run: |
        pytest --ignore=fossil-main --ignore=ex/benchmarks-deterministic/FOSSIL-versions
